# Generated by Django 6.1

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacoes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacao',
            name='conteudo_ajudou',
            field=models.IntegerField(choices=[(1, 'Discordo totalmente'), (2, 'Discordo'), (3, 'Neutro'), (4, 'Concordo'), (5, 'Concordo totalmente')], default=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='experiencia_investimentos',
            field=models.IntegerField(choices=[(1, 'Nenhuma'), (2, 'Iniciante'), (3, 'Intermediária'), (4, 'Avançada')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='faixa_etaria',
            field=models.CharField(choices=[('ATE_18', 'Até 18 anos'), ('19_25', '19 a 25 anos'), ('26_35', '26 a 35 anos'), ('36_45', '36 a 45 anos'), ('46_60', '46 a 60 anos'), ('MAIS_60', 'Mais de 60 anos')], default='19_25', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='faixa_renda_familiar',
            field=models.CharField(choices=[('ATE_2000', 'Até R$ 2.000'), ('2000_5000', 'R$ 2.000 a R$ 5.000'), ('5000_10000', 'R$ 5.000 a R$ 10.000'), ('MAIS_10000', 'Acima de R$ 10.000'), ('NAO_INFORMAR', 'Prefiro não informar')], default='NAO_INFORMAR', max_length=13),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='sexo',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro'), ('NI', 'Prefiro não informar')], default='NI', max_length=2),
            preserve_default=False,
        ),
    ]
