# Generated by Django 6.1 on 2026-08-20 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacoes', '0002_avaliacao_conteudo_ajudou_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacao',
            name='experiencia_investimentos',
            field=models.IntegerField(choices=[(1, 'Nenhuma (nunca investi)'), (2, 'Iniciante (poupança, Tesouro Direto, CDB)'), (3, 'Intermediária (ações, fundos imobiliários, ETFs)'), (4, 'Avançada (derivativos, day trade, fundos multimercado)')]),
        ),
    ]
