# Generated by Django 6.1 on 2026-08-20 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacoes', '0003_alter_avaliacao_experiencia_investimentos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacao',
            name='nota',
            field=models.IntegerField(choices=[(1, 'Muito ruim'), (2, 'Ruim'), (3, 'Regular'), (4, 'Bom'), (5, 'Excelente')]),
        ),
    ]
