# Generated by Django 6.1 on 2026-08-20 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacoes', '0004_alter_avaliacao_nota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacao',
            name='nota',
            field=models.IntegerField(choices=[(1, 'Muito ruim'), (2, 'Ruim'), (3, 'Regular'), (4, 'Bom'), (5, 'Excelente')], verbose_name='Navegação no site'),
        ),
    ]
