# Generated by Django 6.1 on 2026-08-16 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artigo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('slug', models.SlugField(help_text='Usado na URL do artigo, gerado a partir do título.', max_length=220, unique=True)),
                ('resumo', models.CharField(help_text='Texto curto exibido na listagem.', max_length=300)),
                ('corpo', models.TextField(help_text='Conteúdo completo do artigo (aceita texto simples).')),
                ('categoria', models.CharField(choices=[('FUNDAMENTOS', 'Fundamentos'), ('RENDA_FIXA', 'Renda fixa'), ('RENDA_VARIAVEL', 'Renda variável'), ('ANALISE_QUANTITATIVA', 'Análise quantitativa')], default='FUNDAMENTOS', max_length=30)),
                ('publicado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-publicado_em'],
            },
        ),
    ]
