# Generated by Django 6.1 on 2026-08-18 15:51

from django.db import migrations, models


def marcar_artigos_existentes_como_publicados(apps, schema_editor):
    # Artigos criados antes deste campo existir já estavam visíveis no site;
    # sem isto, ganhariam o default RASCUNHO e sumiriam da página até
    # republicação manual.
    Artigo = apps.get_model('conteudo', 'Artigo')
    Artigo.objects.update(status='PUBLICADO')


class Migration(migrations.Migration):

    dependencies = [
        ('conteudo', '0002_artigos_exemplo'),
    ]

    operations = [
        migrations.AddField(
            model_name='artigo',
            name='status',
            field=models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('PUBLICADO', 'Publicado')], default='RASCUNHO', max_length=20),
        ),
        migrations.AlterField(
            model_name='artigo',
            name='corpo',
            field=models.TextField(help_text='Conteúdo completo do artigo (aceita um subconjunto seguro de HTML).'),
        ),
        migrations.RunPython(marcar_artigos_existentes_como_publicados, migrations.RunPython.noop),
    ]
